default_language_version:
    python: python3.12 # Using .python-version would be nice
exclude: |
    (?x)^(
        includes\.sh
    )$
repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2024.39.1
      hooks:
          - id: codespell
          - id: dot-yaml
          - id: includes-sh
          - id: mailmap
          - id: prettier-write
          - id: shellcheck
          - id: shfmt
          - id: uv-pip-check
          - id: uv-pip-compile
          - id: yamllint
    - repo: local
      hooks:
          - id: actionlint
            # Neither comments in check.yaml nor .shellcheckrc seem to work
            # Sourcing includes.sh without arguments is common
            entry: env SHELLCHECK_OPTS=--exclude=SC2119 actionlint
            files: ^\.github/workflows/
            language: system
            name: actionlint
            types:
                - yaml
