default_language_version:
    python: python3.12 # Using .python-version would be nice
exclude: |
    (?x)^(
        includes\.sh
    )$
repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2024.39.1
      hooks:
          - id: codespell
          - id: dot-yaml
          - id: includes-sh
          - id: mailmap
          - id: shellcheck
          - id: shfmt
          - id: uv-pip-check
          - id: uv-pip-compile
          - id: yamllint
