jobs:
    plugin_test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v3
              with:
                  command: zed --help

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - main
    pull_request:
